var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/city-news/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0rdcdr0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0s9ewgp.js")
R.c("server/chunks/ssr/[root-of-the-server]__0y~gs73._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/_0o4ky3e._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_city-news_page_actions_0c5.mll.js")
R.m(53551)
module.exports=R.m(53551).exports
