var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/component/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lbz-fr._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0q-l-1x.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ffx97n._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/app_layout_tsx_13yf0ls._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_component_page_actions_0t.wn80.js")
R.m(35408)
module.exports=R.m(35408).exports
