var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/component/city-news/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0k73.70._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_10zt0qu.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ffx97n._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/app_layout_tsx_13yf0ls._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_component_city-news_page_actions_02et5ry.js")
R.m(83233)
module.exports=R.m(83233).exports
