// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[slug]" | "/batterytech" | "/batterytech/[slug]" | "/charging" | "/charging/[slug]" | "/city-news" | "/city-news/[slug]" | "/component" | "/component/city-news" | "/component/city-news/[slug]" | "/dashboard" | "/dashboard/comments" | "/dashboard/news" | "/dashboard/superadmin" | "/dashboard/users" | "/lib/login" | "/lib/signup" | "/login" | "/market" | "/market/[slug]" | "/policy" | "/policy/[slug]" | "/signup" | "/startup" | "/startup/[slug]" | "/vehicles" | "/vehicles/[slug]"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/[slug]": { "slug": string; }
  "/batterytech": {}
  "/batterytech/[slug]": { "slug": string; }
  "/charging": {}
  "/charging/[slug]": { "slug": string; }
  "/city-news": {}
  "/city-news/[slug]": { "slug": string; }
  "/component": {}
  "/component/city-news": {}
  "/component/city-news/[slug]": { "slug": string; }
  "/dashboard": {}
  "/dashboard/comments": {}
  "/dashboard/news": {}
  "/dashboard/superadmin": {}
  "/dashboard/users": {}
  "/lib/login": {}
  "/lib/signup": {}
  "/login": {}
  "/market": {}
  "/market/[slug]": { "slug": string; }
  "/policy": {}
  "/policy/[slug]": { "slug": string; }
  "/signup": {}
  "/startup": {}
  "/startup/[slug]": { "slug": string; }
  "/vehicles": {}
  "/vehicles/[slug]": { "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
