// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/batterytech/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/batterytech/[slug]">> = Specific
  const handler = {} as typeof import("../../app/batterytech/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/batterytech/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/batterytech">> = Specific
  const handler = {} as typeof import("../../app/batterytech/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/charging/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/charging/[slug]">> = Specific
  const handler = {} as typeof import("../../app/charging/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/charging/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/charging">> = Specific
  const handler = {} as typeof import("../../app/charging/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/city-news/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/city-news/[slug]">> = Specific
  const handler = {} as typeof import("../../app/city-news/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/city-news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/city-news">> = Specific
  const handler = {} as typeof import("../../app/city-news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/component/city-news/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/component/city-news/[slug]">> = Specific
  const handler = {} as typeof import("../../app/component/city-news/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/component/city-news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/component/city-news">> = Specific
  const handler = {} as typeof import("../../app/component/city-news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/component/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/component">> = Specific
  const handler = {} as typeof import("../../app/component/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/comments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/comments">> = Specific
  const handler = {} as typeof import("../../app/dashboard/comments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/news">> = Specific
  const handler = {} as typeof import("../../app/dashboard/news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/superadmin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/superadmin">> = Specific
  const handler = {} as typeof import("../../app/dashboard/superadmin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/users">> = Specific
  const handler = {} as typeof import("../../app/dashboard/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lib/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lib/login">> = Specific
  const handler = {} as typeof import("../../app/lib/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lib/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lib/signup">> = Specific
  const handler = {} as typeof import("../../app/lib/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/market/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/market/[slug]">> = Specific
  const handler = {} as typeof import("../../app/market/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/market/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/market">> = Specific
  const handler = {} as typeof import("../../app/market/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/policy/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/policy/[slug]">> = Specific
  const handler = {} as typeof import("../../app/policy/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/policy">> = Specific
  const handler = {} as typeof import("../../app/policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/startup/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/startup/[slug]">> = Specific
  const handler = {} as typeof import("../../app/startup/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/startup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/startup">> = Specific
  const handler = {} as typeof import("../../app/startup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vehicles/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vehicles/[slug]">> = Specific
  const handler = {} as typeof import("../../app/vehicles/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vehicles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vehicles">> = Specific
  const handler = {} as typeof import("../../app/vehicles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
